name: Ubuntu RDP with Ngrok

on: [push]

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo adduser github
        sudo usermod -aG sudo github
        echo 'github:password' | sudo chpasswd  # Replace 'password' with a secure password

    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update && sudo apt-get install ngrok

    - name: Start Ngrok
      run: |
        ngrok authtoken 2hfvYeIbEcWJhPyr02JxWLt0eph_7ChP5LHejGk8AWNDB3q1p
        ngrok tcp 3389 &
      continue-on-error: true

    - name: Get Ngrok URL
      run: |
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt
      continue-on-error: true

    - name: Print Ngrok URL
      run: |
        cat ngrok_url.txt
        echo "RDP is set up. Connect using the above Ngrok URL."

    - name: Perform post-checkout tasks
      run: |
        # Add your post-checkout commands here
        echo "Performing post-checkout tasks..."
        # Example command: Listing the contents of the repository
        ls -la
        # You can add other commands as needed
