name: Ubuntu RDP with ngrok

on: [push]

jobs:
  rdp-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install xfce4 and xrdp
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils xrdp
        sudo systemctl enable xrdp
        sudo adduser github
        echo 'github:github' | sudo chpasswd
        sudo adduser github sudo
        echo 'xfce4-session' > /home/github/.xsession
        sudo systemctl restart xrdp
        sudo ufw allow 3389/tcp
        sudo ufw enable

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
        tar -xvzf ngrok.tgz
        sudo mv ngrok /usr/local/bin/

    - name: Start ngrok
      env:
        NGROK_TOKEN: 2hfusNPJ1KZmfwFd3ICIMzNRJJO_7dGHQqvm41hWPtFu1mzPE
      run: |
        ngrok config add-authtoken 2hfusNPJ1KZmfwFd3ICIMzNRJJO_7dGHQqvm41hWPtFu1mzPE
        nohup ngrok tcp 3389 --log=stdout &

    - name: Display ngrok URL
      run: |
        sleep 10
        curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
